#!/usr/bin/env python3
"""Generate compatibility lua_packages.txt from catalog metadata.
从 catalog 元数据生成兼容 lua_packages.txt。
"""

from __future__ import annotations

from pathlib import Path

from catalog_common import (
    build_template_context,
    load_bundle,
    load_package_records,
    render_placeholders,
    repo_root,
    write_text,
)


def render_package_line(package_record: dict) -> str:
    """Render one `pkg ...` line.
    渲染一行 `pkg ...`。
    """

    version = package_record.get("version")
    if version:
        return f"pkg {package_record['rock_name']} {version}"
    return f"pkg {package_record['rock_name']}"


def render_entry(prefix: str, values: list[str]) -> str:
    """Render one indented compatibility entry line.
    渲染一条带缩进的兼容配置行。
    """

    return f"  {prefix} " + " ".join(values)


def render_legacy_lines(package_record: dict) -> list[str]:
    """Render legacy compatibility lines for one package record.
    为单个 package 记录渲染 legacy 兼容行。
    """

    context = build_template_context(package_record)
    legacy_config = package_record.get("legacy_config", {})
    lines: list[str] = [render_package_line(package_record)]

    for install in legacy_config.get("install", []):
        target_ref = render_placeholders(install["target_ref"], context)
        lines.append(render_entry("install", [install["os"], target_ref]))

    for arg in legacy_config.get("args", []):
        value = render_placeholders(arg["single_arg"], context)
        lines.append(render_entry("arg", [arg["os"], value]))

    for env in legacy_config.get("env", []):
        value_ref = render_placeholders(env["value_ref"], context)
        lines.append(render_entry("env", [env["os"], env["name"], value_ref]))

    for dependency in legacy_config.get("dependencies", []):
        url_or_hint = render_placeholders(dependency["url_or_hint"], context)
        lines.append(
            render_entry(
                "dep",
                [
                    dependency["name"],
                    dependency["os"],
                    dependency["method"],
                    url_or_hint,
                ],
            )
        )

    for depvar in legacy_config.get("depvars", []):
        value_ref = render_placeholders(depvar["value_ref"], context)
        lines.append(
            render_entry(
                "depvar",
                [depvar["dep_name"], depvar["os"], depvar["var_name"], value_ref],
            )
        )

    return lines


def main() -> int:
    """Export the compatibility file defined by bundle metadata.
    导出 bundle 元数据定义的兼容文件。
    """

    root = repo_root()
    bundle = load_bundle(root)
    package_records = load_package_records(bundle, root)
    category_order = bundle.get("category_order", [])
    category_groups: dict[str, list[dict]] = {name: [] for name in category_order}
    for record in package_records:
        category_groups.setdefault(record["category"], []).append(record)

    lines = [
        "# Generated by scripts/export_lua_packages_txt.py.",
        "# 由 scripts/export_lua_packages_txt.py 自动生成。",
        "# Do not edit this file by hand.",
        "# 请勿手工修改此文件。",
        "",
    ]

    for category in category_order:
        records = category_groups.get(category, [])
        if not records:
            continue
        lines.append(f"# {category}")
        for record in records:
            lines.extend(render_legacy_lines(record))
            lines.append("")

    output_path = root / bundle["generated"]["lua_packages_txt"]
    write_text(output_path, "\n".join(lines).rstrip() + "\n")
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
